name: Node.js Script

on:
  push:
    tags:
      - "*"
jobs:
  node-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup node
        uses: actions/setup-node@v2
      - run: npm run build
      - name: Commit files
        run: |
          git add -A  
          git config --local user.email "160714+townland-bot[bot]@users.noreply.github.com"
          git config --local user.name "townland-bot[bot]"
          git commit -m "Updated interface by Townland Bot" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}